apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cf-workloads
  namespace: {{ .Values.workloadsNamespace }}
spec:
  maxUnavailable: 0
  selector:
    matchExpressions:
    - key: cloudfoundry.org/app-guid
      operator: Exists
