# Set resource requests and limits for deployments
# When false, no resource requests/limits will be set
# When true, resource requests/limits configurations for individual components will be applied
setResources: true

resources:
  requests:
    cpu: 500m
    memory: 128Mi

image:
  repository: ghcr.io/cloudfoundry/k8s-garden-client
  pullPolicy: IfNotPresent
  tag: ~

instanceIdentityCA: instance-identity

locketAddress: locket.default.svc.cluster.local:8891
bbsAddress: bbs.default.svc.cluster.local:8889
advertiseDomain: cell.127-0-0-1.nip.io
ca_crt: ~
