resources:
  requests:
    cpu: 500m
    memory: 128Mi

image:
  repository: ghcr.io/cloudfoundry/k8s/rep
  pullPolicy: IfNotPresent
  tag: ~

instanceIdentityCA: instance-identity
loggregatorCertificateSecret: ~

locketAddress: locket.default.svc.cluster.local:8891
bbsAddress: bbs.default.svc.cluster.local:8889
advertiseDomain: cell.127-0-0-1.nip.io
caCertificate: ~

fileServer:
  address: http://file-server.default.svc.cluster.local:8080

stacks:
  cflinuxfs4: ghcr.io/cloudfoundry/k8s/cflinuxfs4:1.304.0

workloadsNamespace: cf-workloads

nodeSelector:
  cloudfoundry.org/cell: "true"

tolerations:
  - key: cloudfoundry.org/cell
    operator: Equal
    value: "true"
    effect: NoSchedule
